Pause Play Functionality
MeldCX/matrix-component-camera-barcode-scanner-example pull request #2
Opened 2019-12-03 02:44 UTC by billyendres

- Add pause play feature for camera app
- Test on Chromebox Commercial
- Remove camera light on pause function

2019-12-03 05:07 UTC, JacobWischnatAopen commented on index.html
> +      let reader = document.querySelector("m-camera-barcode-scanner");
Hey Billy, This let can stay as a const? Like it was previously?

2019-12-03 05:08 UTC, JacobWischnatAopen requested changes
IGNORE ME, I AM DUMB

2019-12-03 05:10 UTC, JacobWischnatAopen approved these changes

2019-12-04 05:06 UTC, MileAit requested changes
1) Please publish the latest version of `@meldcx/matrix-component-camera-barcode-scanner` to NPM (should be `1.0.6`)
2) Please bump the dependency version in `package.json` to `1.0.6`
3) Please switch back to the reference instead of copying the full implementation into example
4) Please switch back to the previous formatting (single quotes in scripts)
5) Please update readme
6) Please remove the `dist`, this is an example - not a production app

NPM URL to validate: 
https://www.npmjs.com/package/@meldcx/matrix-component-camera-barcode-scanner

2019-12-05 00:03 UTC, MileAit requested changes
Several more things left to do:
1. Please switch back to the previous formatting (single quotes in scripts)
2. Please add the new `pause()` example into the `index.html`
3. Please update the `readme.md` with the description on how to use the new `pause()` method

2019-12-05 03:56 UTC, MileAit approved these changes

2019-12-05 04:08 UTC, merged